# Generated by Django 4.1.6 on 2023-06-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='subtitles_file',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
