# Generated by Django 4.1.6 on 2023-06-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audify', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.CharField(blank=True, default='00:00:00', max_length=8),
        ),
    ]
