# Generated by Django 4.1.6 on 2023-06-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audify', '0007_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='source_type',
            field=models.CharField(choices=[('file', 'File'), ('youtube', 'Link')], max_length=10),
        ),
    ]
