# Generated by Django 4.1.6 on 2023-06-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audify', '0008_alter_video_source_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='youtube_link',
            new_name='link',
        ),
        migrations.AlterField(
            model_name='video',
            name='source_type',
            field=models.CharField(choices=[('file', 'File'), ('youtube', 'Youtube Link'), ('facebook', 'Facebook Link')], max_length=10),
        ),
    ]
