# Generated by Django 4.1.6 on 2023-06-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audify', '0009_rename_youtube_link_video_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='audio/'),
        ),
    ]
