# Generated by Django 4.1.6 on 2023-06-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audify', '0010_alter_video_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='audios/'),
        ),
    ]
