# Generated by Django 4.1.6 on 2023-07-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audify', '0011_alter_video_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='source_type',
            field=models.CharField(choices=[('file', 'File'), ('youtube', 'Youtube Link'), ('facebook', 'Facebook Link'), ('twitch', 'Twitch Link')], max_length=10),
        ),
    ]
